name: CI Pipeline

on:
  workflow_run:
    workflows: ["Lint"]
    branches: ["main"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to github container registry
        env:
          CR_PAT: ${{secrets.GITHUB_TOKEN}}
        run: echo $CR_PAT | docker login ghcr.io -u yashgo0018 --password-stdin
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/yashgo0018/maci-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
